<?php

return [
    'adoption_bands' => [
        [
            'id' => 'founders',
            'name' => 'Founders',
            'price_label' => 'Free',
            'start_users' => 0,
            'end_users' => 100,
            'summary' => 'First 100 total platform users join for free.',
        ],
        [
            'id' => 'seed',
            'name' => 'Seed',
            'price_label' => '$1/mo',
            'start_users' => 101,
            'end_users' => 250,
            'summary' => 'The first paid cohort starts at a symbolic entry price.',
        ],
        [
            'id' => 'makers',
            'name' => 'Makers',
            'price_label' => '$3/mo',
            'start_users' => 251,
            'end_users' => 500,
            'summary' => 'Pricing rises gradually while the product is still early.',
        ],
        [
            'id' => 'builders',
            'name' => 'Builders',
            'price_label' => '$6/mo',
            'start_users' => 501,
            'end_users' => 750,
            'summary' => 'A mid-growth milestone for teams joining later.',
        ],
        [
            'id' => 'launch',
            'name' => 'Launch',
            'price_label' => '$9/mo',
            'start_users' => 751,
            'end_users' => 1000,
            'summary' => 'The last pre-scale cohort before broader traction.',
        ],
        [
            'id' => 'scale',
            'name' => 'Scale',
            'price_label' => '$14/mo',
            'start_users' => 1001,
            'end_users' => 10000,
            'summary' => 'Stable pricing for the main growth stage.',
        ],
        [
            'id' => 'forever',
            'name' => 'Stable',
            'price_label' => '$14/mo',
            'start_users' => 10001,
            'end_users' => null,
            'summary' => 'The ceiling price stays flat once the platform is mature.',
        ],
    ],

    'plans' => [
        'free' => [
            'name' => 'Free',
            'price_label' => 'Free',
            'billing_type' => 'none',
            'monthly_quota' => 20,
            'features' => [
                'First adopter band',
                'Free for the first 100 total users',
                'Up to 20 exports each month',
                'Basic support',
            ],
        ],
        'launch' => [
            'name' => 'Launch',
            'price_label' => 'Band pricing',
            'billing_type' => 'stripe',
            'stripe_price_id' => env('STRIPE_PRICE_LAUNCH_MONTHLY'),
            'monthly_quota' => 150,
            'features' => [
                'Early paid adoption bands',
                'Price rises gradually from $1 to $9',
                'Up to 150 exports each month',
                'Priority support',
                'Ideal before the platform crosses 1,000 users',
            ],
        ],
        'growth' => [
            'name' => 'Growth',
            'price_label' => '$14/mo',
            'billing_type' => 'stripe',
            'stripe_price_id' => env('STRIPE_PRICE_GROWTH_MONTHLY'),
            'monthly_quota' => 600,
            'features' => [
                'Stable public pricing band',
                'Applies after 1,000 total users',
                'Up to 600 exports each month',
                'Price stays capped from 10,000+ users onward',
            ],
        ],
        'custom' => [
            'name' => 'Custom',
            'price_label' => 'Custom',
            'billing_type' => 'contact',
            'monthly_quota' => null,
            'features' => [
                'Custom onboarding and migration help',
                'Agency or enterprise setup',
                'Priority onboarding',
            ],
        ],
    ],
];
